### ISSUE TITLE
[Feature Request] Autosave

### ISSUE THREAD

**Issue by ghost** [sorge13248/PasteIntoFile#1]
can you add autosave of the content to file without any dialogue and questions? so picture autosaves to file with default name?

**Comment by sorge13248** [comment]
Sure, I'll definitely add it in the next release!

**Comment by sorge13248** [comment]
Autosave feature added. You can download the latest version here: https://github.com/sorge13248/PasteIntoFile/releases/tag/v2.0

Thank you for your contribution on making PasteIntoFile a better FOSS!
